---
title: "Proposal"
author: "The One"
date: "2020/3/30"
output:
  word_document: default
  pdf_document: default
  html_document: default
pagemargins: 2.5
fontsize: 12
---

<style type=""Proposal/css">
	#header {
	    text-align: center;
	}
</style>

# 一.研究背景 
&emsp;&emsp;2019年底在中国武汉开始发现新型冠状病毒，此后近4个月的时间里，中国以及全球各个国家开始不断爆发新型冠状病毒疫情。截止2020年3月30日，中国累计确诊82505例，国外累计确诊651843例；中国累计死亡3313例，国外累计死亡31524例，而且仍在持续增长中，全球疫情形式不容乐观。专家指出新冠病毒主要是以空气中飞沫的形式进行传播，根据一些调查可知，空气中的飞沫会受到气象因素，诸如空气湿度，能见度，风速等的影响。因此，研究气象因素对新冠病毒传播的影响具有很重要的现实意义。 

# 二.研究问题 
&emsp;&emsp;本文主要从气象因素的角度研究新冠病毒传播的影响因素。  

# 三.数据来源 
&emsp;&emsp;气象数据来源于[中国气象数据网](https://data.cma.cn/)，武汉市新型冠状病毒疫情数据来源于狗熊会（公众号）。 
 
# 四.研究方法 
&emsp;&emsp;在研究气象因素对传染病影响的文献中，采用的模型很多，包括GAM模型、神经网络模型等。最终使用的方法将根据数据实际拟合效果来确定。
 
# 五.问题及挑战 
1. 小组成员是第一次在实例中运用神经网络模型和GAM模型，理论以及实践都不是很成熟。 
2. 气象因子包括的内容很多，有气压、气温、湿度、风速、降水、日照等，具体选择用哪些变量来研究新冠肺炎还需要结合研究的实际情况继续讨论。 
3. 新冠肺炎从感染到发病有一段时间的潜伏期，我们把它称为滞后效应，对滞后效应时长的确定能够对疫情的前期控制提供有效的帮助，如何确定具体的滞后期也是我们需要进一步研究的问题。 
 
# 六.解决办法 
1. 在有限的时间内仔细研究神经网络模型与GAM模型，通过查找相关资料，熟练使用软件运用模型。 
2. 对于气象因素的选择问题，可以先将所有的因素均放进模型，然后逐步排除不显著的变量。 
3. 对于滞后效应问题，通过比较不同滞后期下模型的预测精度来确定最合适的滞后期。 
 




