---
title: "**武汉地区气象数据对新型冠状病毒肺炎疫情的影响分析**"
author:
  - 刘颖
  - 张晓蕊
  - 刘光子
  - 曹雪娇
  - 李雪丽
documentclass: ctexart
geometry: "left=2.5cm,right=2.5cm,top=2.5cm,bottom=2.5cm"
fontsize: 12pt
pagestyle: empty
output: rticles::ctex
classoption: "hyperref,"
---
# 摘要

&emsp;&emsp;湖北省武汉市在2019年底爆发的新型冠状病毒肺炎（COVID-19）对人们的生活和工作产生很大影响。截至2020年3月31日，武汉市累计确诊50007人，累计死亡2553人。传染病学家已经发现COVID-19的主要传播途径是呼吸道飞沫和接触传播。为探讨气象因素和大气污染物对COVID-19的影响，本文选取了2020年1月20日至2020年3月31日的数据。首先，进行相关分析，其次，建立了广义相加模型（GAM）和分布滞后非线性模型（DLNM）。研究表明，气象和大气污染物对COVID-19确诊人数和死亡人数有一定的影响且存在滞后效应。

**关键词：**COVID-19；GAM模型；DLNM模型；相对危险度

# 1 引言

## 1.1 研究背景

## 1.2 文献综述

# 2 模型介绍


## 2.1 广义相加模型

&emsp;&emsp;在流行病学和统计学的应用中，一般使用回归模型探索响应变量和解释变量的线性关系，其中一般线性模型最基础，其严格的基本假设条件是:随机误差项必须服从零均值同方差的正态分布。广义线性模型（Generalized Linear Model，GLM）为了克服一般线性模型的缺点，对假设条件进行推广：①自变量可以适用于连续数据和离散数据，因变量可以是非连续性；②随机误差不一定服从正态分布，可以服从指数分布族（如正态分布、Poisson分布、二项分布等）；③通过连接函数（Link Function）建立响应变量和解释变量之间的数学关系。相比于GLM，由Hastie和Tibshirani于1986年首次提出的广义相加模型（Generalized Additive Model ，GAM）适用范围更广，适用于多种分布类型，多种复杂的非线性关系的分析。GAM对GLM进一步推广条件如下：①自变量与因变量可以为已知或未知关系；②引入半参数.或非参数回归方法建立模型，即模型中的解释成分可以是解释变量本身，也可以是解释变量的基函数形式，其中基函数的形式主要包括非参数平滑函数（如局部移动平均、样条平滑函数）、多项式函数（如自然立方样条函数、B样条函数及其他多项式函数）等。

&emsp;&emsp;广义相加模型的一般形式为：

$$\log[E(Y_t)]=\alpha+\sum_{i=1}^n\beta_i\,X_i+\sum_{j=1}^mf_j(Z_j)$$

&emsp;&emsp;式中，$Y_t$为观察日$t$日的确诊人数或死亡人数；$E(Y_t)$为观察日$t$日的确诊人数或死亡人数的期望值；$X_i$为对因变量产生线性影响的自变量；$\beta_i$为回归模型估计的解释变量系数；$f_j(Z_j)$为样条函数；$Z_j$为对因变量产生非线性影响的变量。

&emsp;&emsp;平滑参数自由度的确定主要有以下几种方法：①参考之前的研究直接给定自由度；②利用广义交叉验证（ Generalized cross validation，GCV）来估计，GCV值越小越好； ③利用赤池信息准则（Akaike information criterion，AIC），依据AIC最小选择自由度。一般而言，参数的平滑自由度越大，模型拟合优度的决定系数R<sup>2</sup>越趋向于1。

&emsp;&emsp;在R中，至少有三个程序包可以拟合广义相加模型，分别是Trevor Hastie和Tibshirani编写的gam程序包，Simon Wood编写的mgcv程序包和Chong gu编写的gcc程序包。gam程序包允许使用不同的平滑函数来拟合模型，但是需要人工选择合适的自由度。mgcv程序包虽然只能选择样条函数作为平滑函数，但是它既可以自动选择合适的自由度，也可以手动的选择自由度。从积极的方面看，自动选择合适的自由度可以减少工作量，避免手动选择带来的任意性。然而，在某些情况下，自动选择可能不能很好的拟合模型，此时，人工选择自由度就显得非常必要了。


## 2.2 分布滞后非线性模型

&emsp;&emsp;空气污染、气象等暴露因素的健康效应均有一定的持续性和滞后性。换言之，人群健康指标（如死亡率、发病率）不仅与当天的暴露水平有关，还可能受昨天乃至十多天前暴露的影响。近年来，分布滞后线性模型的提出使得该问题的研究有了很大的进展，国外目前普遍运用该法研究空气污染的健康效应，但该法的应用前提是暴露-反应关系呈线性。然而，现实研究中有的暴露一反应关系呈现非线性，如气温效应通常呈U型、V型或J型分布,并不适合使用该法。分布滞后非线性模型（Distributed Lag Non-Linear Model，DLNM）同时考虑暴露因素的滞后效应（lag effect）和暴露-反应的非线性关系。

&emsp;&emsp;该模型首先建立基于传统方法的基本模型，可为广义线性模型、广义相加模型以及广义估计方程等；接着对暴露-反应和滞后效应在时间维度的分布给予某些限制，从而估计不同滞后时间的暴露一反应关系，它的核心思想是构建交叉基（cross-basis），对自变量与因变量的关系、滞后效应的分布分别选择合适的基函数，求两个基函数的张力积即得交叉基函数。该模型不仅限于空气污染或气温对人类健康影响的研究，还可推广应用于任何探究预测变量与结局的关系及滞后效应的时间序列研究，甚至有望应用于病例-对照、前瞻性研究等临床试验中。

&emsp;&emsp;为了定量研究大气污染物或气温因素对健康效应的影响，需要对危险度进行评估。根据GAM模型估计的暴露-反应回归系数β，计算相对危险度（relative risk，RR）：
$$RR=e^{β*IQR}$$
&emsp;&emsp;式中：$IQR$为四分位距，$IQR$ = 第三四分位数$Q_3$  - 第一四分位数$Q_1$。

&emsp;&emsp;然后计算RR的95%置信区间（95%CI）：
$$95\%CI=[e^{(β-1.96Se)*IQR},e^{(β+1.96Se)*IQR}]$$
&emsp;&emsp;式中：$Se$为标准误。


&emsp;&emsp;在R中，可以使用Antonio Gasparrini、Ben Armstrong和Fabian Scheipl编写的dlnm程序包来构建DLNM模型。
# 3 描述性统计分析

## 3.1 数据说明

# 4 实证分析

## 4.1 相关分析

&emsp;&emsp;相关分析是一种简单易行的测量定量数据之间的关系情况的分析方法，可以分析包括变量间的关系情况以及关系强弱程度等。比如，身高和体重的相关性；降水量与河流水位的相关性；工作压力与心理健康的相关性等。相关分析主要研究借助于若干分析指标（如相关系数、相关指数等）对变量间的依存关系的紧密程度作测定。它的适用范围很广，理论上讲，凡是考察两个变量相关性，都可以叫做相关分析。常见的相关系数有三类：Pearson相关系数、Spearman相关系数和Kendall相关系数。本文通过对气象数据和空气污染数据与新冠肺炎当日新增确诊数和当日新增死亡数之间的相关性分析，希望得出气象指标和空气污染指标与新冠肺炎之间的关系。由于传染病致病具有一定的滞后效应，所以在分析相关性时引入滞后期。分析结果如表4-1，4-2所示：

<center>表4-1   气象，空气污染指标与当日新增确诊数相关性系数与显著性水平汇总表</center>
滞后期|0|1|2|3|4|5|6|7 
:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:
PM2.5|0.00<br>(0.97)|0.04<br>(0.74)|0.08<br>(0.52)|0.08<br>(0.51)|0.13<br>(0.29)|0.10<br>(0.42)|0.11<br>(0.40)|0.14<br>(0.28)   
PM10|-0.20<br>(0.10)|-0.18<br>(0.14)|-0.18<br>(0.14)|-0.19<br>(0.12)|-0.16<br>(0.20)|-0.22<br>(0.08)|-0.21<br>(0.10)|-0.18<br>(0.15)
SO2|-0.23<br>(0.05)|-0.33<br>(0.01)|-0.33<br>(0.01)|-0.35<br>(0.00)|-0.34<br>(0.010|-0.39<br>(0.00)|-0.38<br>(0.00)|-0.41<br>(0.00)
CO|-0.13<br>(0.29)|-0.24<br>(0.04)|-0.25<br>(0.04)|-0.30<br>(0.01)|-0.27<br>(0.03)|-0.42<br>(0.00)|-0.43<br>(0.00)|-0.42<br>(0.00)
NO2|-0.09<br>(0.47)|-0.12<br>(0.32)|-0.11<br>(0.37)|-0.12<br>(0.34)|-0.06<br>(0.65)|-0.07<br>(0.58)|-0.07<br>(0.57)|-0.09<br>(0.50)
O3|-0.19<br>(0.12)|-0.23<br>(0.06)|-0.29<br>(0.02)|-0.28<br>(0.02)|-0.27<br>(0.03)|-0.30<br>(0.01)|-0.32<br>(0.01)|-0.37<br>(0.00)
AT|-0.54<br>(0.00)|-0.60<br>(0.00)|-0.60<br>(0.00)|-0.62<br>(0.00)|-0.64<br>(0.00)|-0.69<br>(0.00)|-0.75<br>(0.00)|-0.79<br>(0.00)   
SUN|0.10<br>(0.43)|0.00<br>(0.98)|-0.04<br>(0.74)|-0.07<br>(0.58)|-0.06<br>(0.63)|-0.09<br>(0.48)|-0.08<br>(0.51)|-0.12<br>(0.35)
RH|0.11<br>(0.35)|0.14<br>(0.24)|0.15<br>(0.21)|0.20<br>(0.10)|0.21<br>(0.09)|0.21<br>(0.09)|0.26<br>(0.04)|0.30<br>(0.02)
DTR|-0.09<br>(0.45)|-0.18<br>(0.14)|-0.23<br>(0.06)|-0.25<br>(0.04)|-0.24<br>(0.05)|-0.29<br>(0.02)|-0.31<br>(0.01)|-0.32<br>(0.01)
WIND|-0.21<br>(0.08)|-0.16<br>(0.18)|-0.12<br>(0.33)|-0.08<br>(0.53)|-0.09<br>(0.48)|-0.09<br>(0.47)|-0.07<br>(0.61)|-0.05<br>(0.69)

&emsp;&emsp;由表4-1可知，在研究气象，空气污染指标对不同滞后期当日新增确诊数的相关性之后发现，相关系数显著的指标有SO2(0)、CO(1)、O3(1)、AT(0)、RH(6)、DTR(3)，括号中表示该指标与当日新增确诊数相关性系数达到显著的滞后期，证明指标SO2、CO、O3、AT、RH、DTR与当日新增确诊数之间存在相关关系，且指标RH与当日新增确诊数为正相关，指标SO2、CO、O3、AT、DTR与与当日新增确诊数为负相关。

<center>表4-2   气象，空气污染指标与当日新增死亡数相关性系数与显著性水平汇总表</center>
滞后期|0|1|2|3|4|5|6|7 
:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:
PM2.5|-0.13<br>(0.02)|-0.07<br>(0.02)|-0.08<br>(0.01)|-0.10<br>(0.01)|-0.10<br>(0.00)|-0.16<br>(0.00)|-0.12<br>(0.00)|-0.07<br>(0.01)   
PM10|-0.27<br>(0.27)|-0.27<br>(0.54)|-0.30<br>(0.51)|-0.34<br>(0.42)|-0.38<br>(0.42)|-0.41<br>(0.21)|-0.39<br>(0.35)|-0.34<br>(0.59)
SO2|-0.12<br>(0.31)|-0.19<br>(0.11)|-0.25<br>(0.04)|-0.32<br>(0.01)|-0.35<br>(0.00)|-0.42<br>(0.00)|-0.45<br>(0.00)|-0.46<br>(0.00)
CO|-0.14<br>(0.25)|-0.21<br>(0.08)|-0.28<br>(0.02)|-0.36<br>(0.00)|-0.40<br>(0.00)|-0.48<br>(0.00)|-0.43<br>(0.00)|-0.41<br>(0.00)
NO2|-0.13<br>(0.28)|-0.14<br>(0.26)|-0.13<br>(0.31)|-0.16<br>(0.18)|-0.19<br>(0.13)|-0.21<br>(0.09)|-0.24<br>(0.06)|-0.20<br>(0.12)
O3|-0.04<br>(0.75)|-0.11<br>(0.35)|-0.17<br>(0.16)|-0.18<br>(0.14)|-0.29<br>(0.02)|-0.30<br>(0.01)|-0.37<br>(0.00)|0.42<br>(0.00)
AT|-0.29<br>(0.01)|-0.41<br>(0.00)|-0.50<br>(0.00)|-0.59<br>(0.00)|-0.64<br>(0.00)|-0.68<br>(0.00)|-0.68<br>(0.00)|-0.68<br>(0.00)   
DTR|0.15<br>(0.21)|0.10<br>(0.41)|0.07<br>(0.60)|0.07<br>(0.60)|-0.04<br>(0.78)|-0.03<br>(0.80)|-0.10<br>(0.43)|-0.14<br>(0.27)
RH|-0.04<br>(0.74)|-0.02<br>(0.85)|0.00<br>(0.98)|0.10<br>(0.42)|0.12<br>(0.34)|0.20<br>(0.11)|0.28<br>(0.03)|0.34<br>(0.01)
SUN|0.03<br>(0.81)|-0.05<br>(0.67)|-0.06<br>(0.63)|-0.07<br>(0.58)|-0.18<br>(0.16)|-0.23<br>(0.07)|-0.32<br>(0.01)|-0.34<br>(0.01)
WIND|-0.19<br>(0.12)|-0.17<br>(0.17)|-0.20<br>(0.09)|-0.19<br>(0.12)|-0.11<br>(0.38)|-0.08<br>(0.53)|-0.01<br>(0.94)|0.03<br>(0.81)

&emsp;&emsp;由表4-可知，在研究气象，空气污染指标对不同滞后期当日新增死亡数的相关性之后发现，相关系数显著的指标有PM2.5(0)、SO2(2)、CO(2)、O3(4)、AT(0)、RH(6)、SUN(6)，括号中表示该指标与当日新增确诊数相关性系数达到显著的后期，证明指标PM2.5、SO2、CO、O3、AT、RH、SUN与当日新增死亡数之间存在相关关系，且指标RH与当日新增死亡数为正相关，指标PM2.5、SO2、CO、O3、AT、SUN与与当日新增确诊数为负相关。

## 4.2 气温因素对确诊人数的影响

## 4.3 气温因素对死亡人数的影响

# 5 研究结论

# 6 致谢

&emsp;&emsp;时间如白驹过隙，近四个月的学习生活转瞬即逝。首先感谢闫军教授给予我们很多的指导，使我们的专业知识和科研能力得到了质的提升，同时教授严谨的治学态度及渊博的学识都让我们备受熏陶；其次，感谢同学们所提的问题和建议，使得我们不断完善自己的论文，另外，我们也从大家做的报告中学习到很多新的知识，这将是我们宝贵的财富。

## 贡献声明

&emsp;&emsp;（1）刘颖：负责第四部分第一节相关分析，得出各指标与当日新增确诊数和当日新增死亡数的相关关系。

&emsp;&emsp;（2）张晓蕊：

&emsp;&emsp;（3）刘光子：

&emsp;&emsp;（4）曹雪娇：负责第二部分GAM模型及DLNM模型的介绍，同时编写了部分实证代码。

&emsp;&emsp;（5）李雪丽：


# 参考文献
